export declare const defaultValues: {
    showThreeDots: boolean;
    hideArrowJumper: boolean;
    showQuickJumper: boolean;
    showDoubleArrowJumper: boolean;
    showSizeChanger: boolean;
    isSimple: boolean;
    isChecked: boolean;
    isDefaultChecked: boolean;
    isDisabled: boolean;
    isPartiallyChecked: boolean;
    isFullWidth: boolean;
    isRound: boolean;
    isRotating: boolean;
    isLoading: boolean;
    isAlternative: boolean;
    autoFocus: boolean;
    isMulti: boolean;
    iconRight: boolean;
    iconLeft: boolean;
    isBordered: boolean;
    tabs: ({
        value: string;
        label: string;
        isDisabled?: undefined;
    } | {
        value: string;
        label: string;
        isDisabled: boolean;
    })[];
    className: string;
    direction: string;
    selectDefaultValueOne: string;
    selectDefaultValueTwo: string;
    place: string;
    textOn: string;
    textOff: string;
    primaryButtonContent: string;
    secondaryButtonContent: string;
    iconName: string;
    tooltipType: string;
    event: string;
    eventOff: string;
    type: string;
    size: string;
    position: string;
    children: string;
    value: string;
    selectValue: {
        value: string;
    }[];
    options: {
        value: string;
        label: string;
    }[];
    chosenText: (chosen: string, outOf: string) => {
        chosen: string;
        outOf: string;
    };
    closeText: string;
    submitText: string;
    deleteAllText: string;
    placeholder: string;
    defaultValue: string;
    notificationContent: string;
    notificationTitle: string;
    notificationButonIcon: null;
    content: string;
    messageType: string;
    shape: string;
    width: number;
    height: number;
    pageSizeOptions: number[];
    total: number;
    sortBy: string;
    order: string;
};
