export var defaultValues = {
    isChecked: false,
    isDefaultChecked: false,
    isDisabled: false,
    isPartiallyChecked: false,
    isFullWidth: false,
    isRound: false,
    isRotating: false,
    isLoading: false,
    isAlternative: false,
    autoFocus: false,
    isMulti: false,
    iconRight: false,
    iconLeft: false,
    selectDefaultValueOne: 'value 1',
    selectDefaultValueTwo: 'value 2',
    place: 'top',
    textOn: 'on',
    textOff: 'off',
    iconName: 'hamburger',
    tooltipType: 'dark',
    event: 'mouseenter',
    eventOff: 'mouseleave',
    type: 'default',
    size: 'medium',
    position: 'left',
    children: 'Change me, please 🥺',
    value: 'Change me, please 🥺',
    selectValue: [{ value: 'Change me, please 🥺' }],
    placeholder: 'Change me, please 🥺',
    defaultValue: 'Change me, please 🥺'
};
//# sourceMappingURL=defaultValues.js.map