export const defaultValues = {
  showThreeDots: true,
  hideArrowJumper: false,
  showQuickJumper: false,
  showDoubleArrowJumper: true,
  showSizeChanger: false,
  isSimple: false,
  isChecked: false,
  isDefaultChecked: false,
  isDisabled: false,
  isPartiallyChecked: false,
  isFullWidth: false,
  isRound: false,
  isRotating: false,
  isLoading: false,
  isAlternative: false,
  autoFocus: false,
  isMulti: false,
  iconRight: false,
  iconLeft: false,
  selectDefaultValueOne: 'value 1',
  selectDefaultValueTwo: 'value 2',
  place: 'top',
  textOn: 'on',
  textOff: 'off',
  primaryButtonContent: 'Potvrdit',
  secondaryButtonContent: 'Zavřít',
  iconName: 'hamburger',
  tooltipType: 'dark',
  event: 'mouseenter',
  eventOff: 'mouseleave',
  type: 'default',
  size: 'medium',
  position: 'left',
  children: 'Change me, please 🥺',
  value: 'Change me, please 🥺',
  notFoundMessage: 'Zadaný výraz nebyl nalezen...',
  selectValue: [{ value: 'Change me, please 🥺' }],
  options: [
    { value: 'first option', label: 'First option' },
    { value: 'second option', label: 'Second option' },
    { value: 'third option', label: 'Third option' }
  ],
  closeButton: 'Zavřít',
  submitButton: 'Potvrdit',
  deleteAllButton: 'Odebrat vše',
  placeholder: 'Change me, please 🥺',
  defaultValue: 'Change me, please 🥺',
  notificationContent: 'Change me, please 🥺',
  notificationTitle: 'Notification',
  notificationButonIcon: null,
  content: 'Change me, please 🥺',
  messageType: 'primary',
  shape: 'circle',
  width: 20,
  height: 50,
  pageSizeOptions: [10, 20, 30, 40, 50],
  total: 1000
};
