import React from 'react';
import * as Icons from '../../Icons';
import { StyledIcon } from './Icon.style';

export const IconsMap = {
  arrowsVertical: <Icons.ArrowsVertical/>,
  arrowUp: <Icons.ArrowUp/>,
  arrowDoubleUp: <Icons.ArrowDoubleUp/>,
  arrowRight: <Icons.ArrowRight/>,
  arrowDoubleRight: <Icons.ArrowDoubleRight/>,
  arrowDown: <Icons.ArrowDown/>,
  arrowDoubleDown: <Icons.ArrowDoubleDown/>,
  arrowLeft: <Icons.ArrowLeft/>,
  arrowDoubleLeft: <Icons.ArrowDoubleLeft/>,
  hamburger: <Icons.Hamburger/>,
  loading: <Icons.Loading/>,
  edit: <Icons.Edit/>,
  copy: <Icons.Copy/>,
  check: <Icons.Check/>,
  checkSimple: <Icons.CheckSimple/>,
  users: <Icons.Users/>,
  user: <Icons.User/>,
  upload: <Icons.Upload/>,
  download: <Icons.Download/>,
  trash: <Icons.Trash/>,
  search: <Icons.Search/>,
  table: <Icons.Table/>,
  plus: <Icons.Plus/>,
  logout: <Icons.Logout/>,
  license: <Icons.License/>,
  key: <Icons.Key/>,
  info: <Icons.Info/>,
  import: <Icons.Import/>,
  export: <Icons.Export/>,
  eye: <Icons.Eye/>,
  eyeSlash: <Icons.EyeSlash/>,
  close: <Icons.Close/>,
  clear: <Icons.Clear/>,
  enter: <Icons.Enter/>,
  error: <Icons.Error/>,
  warning: <Icons.Warning/>,
  checkCircle: <Icons.CheckCircle/>,
  calendar: <Icons.Calendar/>,
  calendarAlt: <Icons.CalendarAlt/>,
  question: <Icons.Question/>,
  profile: <Icons.Profile/>,
  zoom: <Icons.Zoom/>,
  home: <Icons.Home/>,
  bookmarks: <Icons.Bookmarks/>,
  tags: <Icons.Tags/>,
  star: <Icons.Star/>,
  note: <Icons.Note/>,
  monitor: <Icons.Monitor/>,
  list: <Icons.List/>,
  listAlt: <Icons.ListAlt/>,
  history: <Icons.History/>,
  folder: <Icons.Folder/>,
  file: <Icons.File/>,
  fileAlt: <Icons.FileAlt/>,
  comment: <Icons.Comment/>,
  calculator: <Icons.Calculator/>,
  book: <Icons.Book/>,
  bookOpened: <Icons.BookOpened/>,
  citex: <Icons.Citex/>,
  zoomIn: <Icons.ZoomIn/>,
  play: <Icons.Play/>,
  flagParagraph: <Icons.FlagParagraph/>,
  flagCzech: <Icons.FlagCzech/>,
  flagComments: <Icons.FlagComments/>,
  flagEU: <Icons.FlagEU/>,
  flagLawCzech: <Icons.FlagLawCzech/>,
  flagLawEU: <Icons.FlagLawEU/>,
  flagLiterature: <Icons.FlagLiterature/>,
  flagSlovakia: <Icons.FlagSlovakia/>,
  threeDots: <Icons.ThreeDots/>,
  filter: <Icons.Filter/>,
  diff: <Icons.Diff/>,
  news: <Icons.News/>,
  folderOpen: <Icons.FolderOpen/>,
  fileCsv: <Icons.FileCsv/>,
  fileDoc: <Icons.FileDoc/>,
  fileJpg: <Icons.FileJpg/>,
  filePdf: <Icons.FilePdf/>,
  filePng: <Icons.FilePng/>,
  filePpt: <Icons.FilePpt/>,
  fileRtf: <Icons.FileRtf/>,
  fileTxt: <Icons.FileTxt/>,
  fileXls: <Icons.FileXls/>,
  fileXml: <Icons.FileXml/>,
  fileZip: <Icons.FileZip/>,
  virus: <Icons.Virus/>,
  facebook: <Icons.Facebook/>,
  google: <Icons.Google/>,
  fileWithoutContent: <Icons.FileWithoutContent/>,
  notification: <Icons.Notification/>,
  creditCard: <Icons.CreditCard/>,
  attachment: <Icons.Attachment/>,
  inProgress: <Icons.InProgress/>,
  phone: <Icons.Phone/>,
  video: <Icons.Video/>,
  crossedPhone: <Icons.CrossedPhone/>,
  crossedCamera: <Icons.CrossedCamera/>,
  microphone: <Icons.Microphone/>,
  crossedMicrophone: <Icons.CrossedMicrophone/>,
  emoji: <Icons.Emoji/>,
  facebookFilled: <Icons.FacebookFilled/>,
  envelope: <Icons.Envelope/>,
  login: <Icons.Login/>,
  plusSquare: <Icons.PlusSquare/>,
  send: <Icons.Send/>,
  cog: <Icons.Cog/>,
  hash: <Icons.Hash/>,
  robot: <Icons.Robot/>,
  switch: <Icons.Switch/>,
  userAdd: <Icons.UserAdd/>,
  building: <Icons.Building/>,
  offer: <Icons.Offer/>,
  prev: <Icons.Prev/>,
  next: <Icons.Next/>,
  external: <Icons.External/>,
  change: <Icons.Change/>,
  print: <Icons.Print/>,
  squaresGrid: <Icons.SquaresGrid/>,
  tag: <Icons.Tag/>,
  timeline: <Icons.Timeline/>,
  brush: <Icons.Brush/>,
  fontSize: <Icons.FontSize/>,
  transformation: <Icons.Transformation/>,
  copyFilled: <Icons.CopyFilled/>,
  messageBubble: <Icons.MessageBubble/>,
  layers: <Icons.Layers/>,
  pencil: <Icons.Pencil/>,
  signout: <Icons.Signout/>,
  userSettings: <Icons.UserSettings/>,
  downloadCloud: <Icons.DownloadCloud/>,
  addressBook: <Icons.AddressBook/>,
  attachmentLeft: <Icons.AttachmentLeft/>,
  back: <Icons.Back/>,
  coinsOverlined: <Icons.CoinsOverlined/>,
  coins: <Icons.Coins/>,
  contextMenu: <Icons.ContextMenu/>,
  downloadAlt: <Icons.DownloadAlt/>,
  externalLink: <Icons.ExternalLink/>,
  lock: <Icons.Lock/>,
  mailClosed: <Icons.MailClosed/>,
  mailOpened: <Icons.MailOpened/>,
  mail: <Icons.Mail/>,
  pdf: <Icons.PDF/>,
  save: <Icons.Save/>,
  starSolid: <Icons.StarSolid/>,
  testConnection: <Icons.TestConnection/>,
  uploadSolid: <Icons.UploadSolid/>,
  bulkDownload: <Icons.BulkDownload/>,
  documentCompare: <Icons.DocumentCompare/>,
  collapse: <Icons.Collapse/>,
  expand: <Icons.Expand/>,
  cart: <Icons.Cart/>,
  ban: <Icons.Ban/>,
  hourGlass: <Icons.HourGlass/>,
  fileAi: <Icons.FileAi/>,
  fileUnknown: <Icons.FileUnknown/>,
  fileJavascript: <Icons.FileJavascript/>,
  fileAvi: <Icons.FileAvi/>,
  fileCss: <Icons.FileCss/>,
  fileGif: <Icons.FileGif/>,
  fileJSON: <Icons.FileJSON/>,
  fileMp3: <Icons.FileMp3/>,
  fileMp4: <Icons.FileMp4/>,
  filePsd: <Icons.FilePsd/>,
  fileSvg: <Icons.FileSvg/>,
  fileHtml: <Icons.FileHtml/>,
  fileExe: <Icons.FileExe/>,
  fileIso: <Icons.FileIso/>,
  fileDbf: <Icons.FileDbf/>,
  fileDwg: <Icons.FileDwg/>,
  zoomOut: <Icons.ZoomOut/>,
  sendFlat: <Icons.SendFlat />,
  thumbUp: <Icons.ThumbUp />,
  undo: <Icons.Undo />,
  commentAlt: <Icons.CommentAlt />,
  messageBubbleAlt: <Icons.MessageBubbleAlt />,
  duotoneArrowTarget: <Icons.DuotoneArrowTarget />,
  duotoneLayers: <Icons.DuotoneLayers />,
  duotoneShield: <Icons.DuotoneShield />,
  duotoneFlags: <Icons.DuotoneFlags />,
  duotoneUniversity: <Icons.DuotoneUniversity />,
  duotoneUsers: <Icons.DuotoneUsers />,
  duotoneList: <Icons.DuotoneList />,
  duotoneCoins: <Icons.DuotoneCoins />,
  duotoneCopy: <Icons.DuotoneCopy />,
  duotoneScreen: <Icons.DuotoneScreen />,
  duotoneFolders: <Icons.DuotoneFolders />,
  duotoneGlobe: <Icons.DuotoneGlobe />,
  archive: <Icons.Archive />,
};

export type IconName = keyof typeof IconsMap;

export interface IconProps extends React.HTMLAttributes<HTMLElement> {
  name: IconName;
  isRotating?: boolean;
}

export const Icon: React.FC<IconProps> = (
  {
    name,
    isRotating,
    ...IProps
  }): React.ReactElement =>
  <StyledIcon isRotating={isRotating} name={name} {...IProps}>
    {IconsMap[name] || <i {...IProps} />}
  </StyledIcon>;


export type Icon = typeof Icon;
